name: rescuedge_responder_app
description: RescuEdge Responder App â€” Ambulance/Hospital/Police emergency response
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.19
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  mqtt_client: ^10.2.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  audioplayers: ^6.0.0
  provider: ^6.1.1
  flutter_riverpod: ^2.4.10
  uuid: ^4.3.3
  intl: ^0.19.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
